### PR TITLE
Add context

### PR DESCRIPTION
**Pull request by Bishoy-at-pieces**

### CODE REVIEW

**Review by mark-at-pieces — APPROVED** [review]

**Comment by mark-at-pieces** [comment]
looks like just some conflicts to resolve then GTG

**Review by moazzem-pixel — COMMENTED** [review]
Need support

**Review by moazzem-pixel — COMMENTED** [review]
Pls do as well

**Comment by Bishoy-at-pieces** [comment]
Hey @moazzem-pixel any issues you are facing?

**Pull request merged**
